### ISSUE TITLE
Placement of the wood chunks

### ISSUE THREAD

**Issue by minter** [mwilbanks/Open-Source-Smoke#2]
Can you provide a little more detail about how you place the wood chunks on the coals?  

Do you get the coals up to 250 dome temp first, then add the layer of wood chunks, plate setter, and meat?

**Comment by mwilbanks** [comment]
Good call. I'll clear that up in the instructions - I'm rewriting it today so it reads more like a recipe instead of a blog post. Usually, I get the fire going with just the coals and a few big chunks of wood and let the temp get up around 50 degrees higher than the actual temp I'll be cooking at. Once it's stable at that temp then I'll let it run for 15 or 20mins to heat up everything. -That way, when I put the meat on the grill and close the lid, it's easier to get back to the temp I want to cook at and wont have to worry about wild temp fluctuations at the beginning. Right before I put the meat on, I add a bunch of wood chunks on top of the burning coals. The longer I'm smoking, the more wood I add.
